### ISSUE TITLE
Instrukcja w konfiguracji nie jest aktualna

### ISSUE THREAD

**Issue by z4nr34l** [SnowdogApps/CreditAgricoleRaty#8]
Aktualnie nie można wysłać URLi do banku poprzez formularz, tylko w formie wiadomości email do opiekuna.

**Comment by JasiukiewiczM** [comment]
Czekamy na odp. ze strony CA

**Comment by z4nr34l** [comment]
Dodatkowo w configu jest pole "hasło", które z tego co się dowiedziałem, nie jest wymagane do integracji sklepu z systemem CA - osobne issue? Jak tak, to wieczorem zrobie MR z poprawką.

**Comment by z4nr34l** [comment]
Zamykam, temat zombie.
